from . import (
    fsm_order,
    problem_solution,
    problem_type,
    # contact_amendment,
    fsm_order_assignment,
    fsm_operation_type,
    fsm_order_type_inherit , 
    fsm_stage_duration,
    fsm_order_stage_tracking,
    fsm_dashboard,
    fsm_order_dashboard,
    fsm_order_replies,
    replies,
    fsm_reply_action,
    fsm_stage_rules,
    product,
    fsm_order_products,
    AddProductWizard,
    fsm_order_line,
    res_partner_fsm_order,
    area_name,
    area_number,
    current_location_wizard,
    res_partner_contacts,
    
)